labels = [
    "Propuesta. Proyecto de Fortalecimiento Familiar Empresarial",
    "Arranca el proyecto con CEDEM",
    "Retiro Estratégico presencial",
    "Proyecto Family Healing. Buscar al asesor ideal para el healing",
    "Consejo Estratégico Grupo Apolo. Identificar lista de posibles candidatos",
    "Los hermanos están de acuerdo en compartir la Creación de Valor con socios y colaboradores",
    "Completar la estructura de Directores en Apolo. Buscar gente estrella",
    "Divisón Markets en GEA se convierte en proyecto de venture",
    "Retiro Estratégico presencial",
    "Arrancan con el Proecto de Internacionalización. Jorge verá el terreno Miami",
    "Surjen discrepancias respecto a la forma de Gobierno de la holding (% para cambios, dividendos, condiciones para entrar a la empresa y puestos)",
    "Cambio en la estructura y tiempos de las reuniones del Consejo de administración (junta directiva) y directores",
    "Retiro Estratégico presencial",
    "GEA Capital. Buscar empresas para crecerlas y vender. Buscar oportunidades en banking (idea de banca digital)",
    "Proyecto de fortalecimiento de Auditoría",
    "CEDEM. Preocupa el tema de alta de foco en ambos grupos",
    "Objetivo del Consejo Estratégico de Apolo - Internacionalización",
    "Reunió virtual con la familia Mini",
    "GEA Capita. Se acepta Visión  Estratégica de buscar una empresa grande donde gobierne la familia",
    "Se toma decisión de buscar salir de top bikes cuanto antes",
    "Family Healing. Se toma decisión de avanzar con Gonzalo Zubieta",
    "Family Healing. Gonzalo Zubieta",
    "Retiro Estratégico presencial",
    "Se mostró una dinámica diferente (efecto de la sesión con Gonzalo Zubieta)",
    "GEA Capita. Saavy le empieza a ir bien, se podría vender a finales 2024",
    "Oferta de compra para Top Bikes (Klos y competencia en el Salvador). Se retira Mauricio Grajeda de la empresa",
    "Sesión de Onboarding del Consejo Estratégico de Grupo Apolo. Definición de estructura",
    "DECV Grupo Apolo",
    "Directivos agobiados, se agregará estructura para liberar a algunos directores",
    "Poblema de enfoque en Grupo Apolo",
    "Reunión de seguimiento con los hermanos. Healing, DECV de Grupo Apolo (conclusiones) y programación del DECV de GEA Capital",
    "Consejo Estratégico de Grupo Apolo. Primera sesión",
    "DECV GEA Capital",
]